dist: bionic
language: ruby
rvm: 2.7
gemfile:
  - Gemfile
cache:
  apt: true
  bundler: true
services:
  - postgresql
  - mysql
  - elasticsearch
  - memcached
  - redis-server
addons:
  postgresql: 10
  apt:
    packages:
      - coinor-libcbc-dev
script: bundle exec appraisal "rake test || true"
before_script:
  - mysqladmin create ultimate_test
  - createdb ultimate_test
  - bundle exec appraisal install
notifications:
  email:
    on_success: never
    on_failure: change
