name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        # caching causes issues - https://github.com/thoughtbot/appraisal/issues/173
        # bundler-cache: true
    - run: bundle install
    - uses: ankane/setup-postgres@v1
      with:
        database: ultimate_test
    - uses: ankane/setup-mysql@v1
      with:
        database: ultimate_test
    - uses: ankane/setup-elasticsearch@v1
    - run: |
        sudo apt-get install memcached
        sudo systemctl start memcached
    - run: |
        sudo apt-get install redis-server
        sudo systemctl start redis
    - run: sudo apt-get install coinor-libcbc-dev libcurl4-openssl-dev
    # for https://github.com/zk-ruby/zookeeper/issues/85
    - run: CFLAGS=-Wno-error=format-overflow gem install zookeeper --version 1.4.11
    - run: bundle exec appraisal install
    - run: bundle exec appraisal "rake test || true"
